### ISSUE TITLE
use the osx_defaults module instead of osx.sh

### ISSUE THREAD

**Issue by mwilliammyers** [dotstrap/ansible-macos#1]
Ref. [tasks/main.yml:15](https://github.com/mkwmms/ansible-osx/blob/579531bae7f3981857be403281b0d92b0f4b840c/tasks/main.yml#L15)

``` yml
# TODO: use the osx_defaults module instead of osx.sh
- name: OS X | configure
  shell: osx.sh
  when: ansible_distribution == 'MacOSX'
  tags:
    - bootstrap
…
```
